### ISSUE TITLE
Lidl has 365 jobs on peviitor.ro and 364 on Lidl.ro

### ISSUE THREAD

**Issue by CristianDoditoiu** [peviitor-ro/firme-peviitor#1]
**Steps to reproduce:**
Access peviitor.ro website
Click on "firme" button
Search for LIDL in the search bar
Verify the number of jobs and click on some of the jobs listed in the list
On lidl.ro click on "Cauta joburi"
**Actual Results:**
Lidl has 365 jobs on peviitor.ro and 364 on Lidl.ro.
**Expected results:**
The number of jobs found on peviitor.ro should be the same as the one on lidl.ro.

**Comment by CristianDoditoiu** [comment]
Bug reopened. Difference between jobs persists.

**Comment by sebiboga** [comment]
please retest like this:
step 1) start the action from here: https://github.com/bbardi/Lidl/actions/workflows/jmeter.yml
step 2) compare number of jobs

if the issue still persist, then we need to ask Bogdan Bardi about the scraper.
I believe during the day LIDL is adding jobs on their website and we are scraping only after few hours.
Let's see if scraper add same number of jobs when run

**Comment by CristianDoditoiu** [comment]
Verified. Status: Passed. It does not reproduce.
