### ISSUE TITLE
InterraTravel - Duplicate company

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/firme-peviitor#100]
**Describe the bug**
Duplicate company on [firme.peviitor](https://firme.peviitor.ro/)

**To Reproduce**
1. Write InterraTravel in the search bar.

**Expected behavior**
The company name appears along with the logo.

**Screenshots**
<img width="181" alt="Screenshot at Feb 16 15-42-57" src="https://github.com/peviitor-ro/firme-peviitor/assets/137428958/14c3bde8-116e-4cb1-8ec7-33321f564d6d">

**Desktop**
 - OS: MacOS
 - Browser: Google chrome

**Comment by lalalaurentiu** [comment]
fixed
