### ISSUE TITLE
Dualit has 13 jobs on peviitor.ro and 15 on their website for Romania

### ISSUE THREAD

**Issue by CristianDoditoiu** [peviitor-ro/firme-peviitor#14]
**Steps to reproduce:**
Access peviitor.ro website
Click on "firme" button
Search for dualit in the search bar
Verify the number of jobs and click on some of the jobs listed in the list
Access https://dualit.ro/careers/

**Actual Results:**
Dualit has 13 jobs on peviitor.ro and 15 on their website for Romania.

**Expected results:**
The number of jobs found on peviitor.ro should be the same as the one on dualit website.

**Comment by sebiboga** [comment]
actions fixed, please retest
https://github.com/d24ioana/dualit/actions/workflows/scraper.yml
