### ISSUE TITLE
Docker has 40 jobs on peviitor.ro and 24 on their website for Romania

### ISSUE THREAD

**Issue by CristianDoditoiu** [peviitor-ro/firme-peviitor#15]
**Steps to reproduce:**
Access peviitor.ro website
Click on "firme" button
Search for docker in the search bar
Verify the number of jobs and click on some of the jobs listed in the list
Access https://www.docker.com/career-openings/

**Actual Results:**
Docker has 40 jobs on peviitor.ro and 24 on their website for Romania. The other jobs (until we make 42) are for other countries.

**Expected results:**
The number of jobs found on peviitor.ro should be the same as the one on https://www.docker.com/career-openings/

**Comment by lalalaurentiu** [comment]
Fixed!
