### ISSUE TITLE
Centric has one job on peviitor and 2 on their website

### ISSUE THREAD

**Issue by CristianDoditoiu** [peviitor-ro/firme-peviitor#19]
**Steps to reproduce:**
Access peviitor.ro website
Click on "firme" button
Search for centric in the search bar
Verify the number of jobs and click on some of the jobs listed in the list
Access https://careers.centric.eu/ro/open-positions/

**Actual Results:**
Centric has 13 jobs on peviitor.ro and 15 on their website for Romania.

**Expected results:**
The number of jobs found on peviitor.ro should be the same as the one on Centric website.

**Comment by lalalaurentiu** [comment]
@andreireporter13  centric returns a string, not a json
<img width="1440" alt="Screenshot 2023-11-23 at 00 25 22" src="https://github.com/peviitor-ro/firme-peviitor/assets/67306273/8715f4c2-11e0-4f29-a122-6e396466989d">
