### ISSUE TITLE
https://firme.peviitor.ro/ is showing the company "bandainamco" twice. One time, the company appears with a wrong name.

### ISSUE THREAD

**Issue by CristianDoditoiu** [peviitor-ro/firme-peviitor#23]
**App, Environment:**
https://firme.peviitor.ro/
Tested on Windows, Chrome browser latest update.

**Steps to reproduce:**

Access peviitor.ro website
1. Click on "firme" button
2. Search for "bandainamco" in the search bar or scroll down to the company logo
3. Click on "bandainamco" Logo
4. Verify the number of jobs and click on the jobs listed in the list
5. Access "c-scale" site to check the number of jobs https://www.bandainamcoent.ro/ro/careers/c-game-programmer/

**Actual Results:**
https://firme.peviitor.ro/ is showing the company "bandainamco" twice. One time, the company appears with a wrong name.
![image](https://github.com/peviitor-ro/firme-peviitor/assets/134626985/f69dc675-71fe-4b87-9e03-fa87c8f1d1dc)

**Expected results**:
We should see the company "bandainamco" only one time and with the correct name

**Comment by lalalaurentiu** [comment]
Fixed!
