### ISSUE TITLE
Leroy Merlin has 20 jobs on peviitor.ro and 82 on jobs.leroymerlin.ro.

### ISSUE THREAD

**Issue by CristianDoditoiu** [peviitor-ro/firme-peviitor#3]
**Steps to reproduce:**
Access peviitor.ro website
Click on "firme" button
Search for leroymerlin in the search bar
Verify the number of jobs and click on some of the jobs shown in the list
On job.leroymerlin.ro click on "Meniu cariere" hamburger menu
Click on "Locuri de munca"

**Actual Results:**
Leroy Merlin has 20 jobs on peviitor.ro and 82 on jobs.leroymerlin.ro.
**Expected results:**
The number of jobs found on peviitor.ro should be the same as the ones on jobs.leroymerlin.ro.

**Comment by sebiboga** [comment]
step 1) start the scraper from here: https://github.com/AdeCLup/leroymerlin/actions/workflows/blank.yml
step 2) check the difference

if issue still persist we need to investigate the scraper

**Comment by CristianDoditoiu** [comment]
Verified. Issue still exists. It still reproduces.
