### ISSUE TITLE
Tecagency has 5 jobs on peviitor.ro and 8 on their website

### ISSUE THREAD

**Issue by CristianDoditoiu** [peviitor-ro/firme-peviitor#4]
**Steps to reproduce:**
Access peviitor.ro website
Click on "firme" button
Search for tecagency in the search bar
Verify the number of jobs and click on some of the jobs listed in the list
Access https://tecss.bamboohr.com/careers
**Actual Results:**
Tecagency has 5 jobs on peviitor.ro and 8 on their website
**Expected results:**
The number of jobs found on peviitor.ro should be the same as the one on (https://tecss.bamboohr.com/careers)

**Comment by sebiboga** [comment]
da, interesant; pe website-ul lor personal promoveaza 6 pozitii, scraperul scoate 5 si pe bamboo sunt 8 ...
refac scraperul sa ia job-urile de pe bamboo

**Comment by sebiboga** [comment]
scraperul a fost rescris pentru a lua joburile de pe bamboo
https://github.com/sebiboga/tec-agency/actions/workflows/jmeter.yml

**Comment by sebiboga** [comment]
good spot!
please restest

**Comment by CristianDoditoiu** [comment]
Verified. Status: Passed. It does not reproduce
