### ISSUE TITLE
Arcadis - LOGO NOT FOUND

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/firme-peviitor#46]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for the company "Arcadis"
3. Check the logo

EXPECTED RESULTS:
The logo for the company "Arcadis" must be the same as the original logo

ACTUAL RESULTS:
The message "Logo not found" is displayed instead of the logo

![image](https://github.com/peviitor-ro/firme-peviitor/assets/122023703/329567ed-c9ae-4436-979f-984ff28e62b7)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
After retesting, the company logo is displayed

![image](https://github.com/peviitor-ro/firme-peviitor/assets/122023703/3a010914-769a-4ca1-b7a2-f2f1b5fae1f5)
