### ISSUE TITLE
SVN - LOGO NOT FOUND

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/firme-peviitor#47]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for the company "SVN"
3. Check the logo

EXPECTED RESULTS:
The logo for the company "SVN" must be the same as the original logo

ACTUAL RESULTS:
The message "Logo not found" is displayed instead of the logo

![image](https://github.com/peviitor-ro/firme-peviitor/assets/122023703/815a5da5-69be-4fa2-b77e-8366699c2b7a)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
After retesting, the company logo is displayed

![image](https://github.com/peviitor-ro/firme-peviitor/assets/122023703/54690448-1420-41a1-8c1c-88bce17ba65c)
