### ISSUE TITLE
Bancatransilvania - Appears twice on firme.peviitor.ro

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/firme-peviitor#48]
ENVIROMENT: production
URL: https://firme.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1) Open URL in browser
2) Type bancatransilvania in Search bar
3) Check the result

EXPECTED RESULTS:
Bancatransilvania appears only once on firme.peviitor.ro

ACTUAL RESULTS:
Bancatransilvania appears twice on firme.peviitor.ro

![cap016](https://github.com/peviitor-ro/firme-peviitor/assets/72222644/97ede747-85f6-4d11-895a-a8c34f78710f)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
After retesting the company appears only once
