### ISSUE TITLE
MSG - The company logo is displayed 2 times on firme.peviitor.ro

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/firme-peviitor#49]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for the company "MSG"
3. Check the logo

EXPECTED RESULTS:
The "MSG" Company logo appears once

ACTUAL RESULTS:
The "MSG" Company logo appears 2 times

![image](https://github.com/peviitor-ro/firme-peviitor/assets/122023703/4e15a181-837e-45f3-a746-f2bab64883ed)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
After retesting, The "MSG" Company logo appears once

![image](https://github.com/peviitor-ro/firme-peviitor/assets/122023703/6f4cc1d8-c125-4efb-aa8f-8607d9875049)
