### ISSUE TITLE
Qualitest has 18 jobs on peviitor.ro and 40 on their website

### ISSUE THREAD

**Issue by CristianDoditoiu** [peviitor-ro/firme-peviitor#5]
**Steps to reproduce:**
Access peviitor.ro website
Click on "firme" button
Search for Qualitest in the search bar
Verify the number of jobs and click on some of the jobs listed in the list
Access https://apply.workable.com/qualitest-1/#jobs
**Actual Results:**
Qualitest has 18 jobs on peviitor.ro and 40 on their website for Romania
**Expected results:**
The number of jobs found on peviitor.ro should be the same as the one on https://apply.workable.com/qualitest-1/#jobs

**Comment by sebiboga** [comment]
good spot!
payload for qualitest has been changed
scraper updated
please recheck

https://github.com/sebiboga/qualitest/actions

**Comment by CristianDoditoiu** [comment]
Verified. Status: Passed. It does not reproduce
