### ISSUE TITLE
Capgemini - LOGO NOT FOUND

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/firme-peviitor#50]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for the company "Capgemini "
3. Check the logo

EXPECTED RESULTS:
The logo for the company "Capgemini " must be the same as the original logo

ACTUAL RESULTS:
The message "Logo not found" is displayed instead of the logo

![image](https://github.com/peviitor-ro/firme-peviitor/assets/122023703/69908b24-fadb-4904-9add-8ac9a007981f)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
After retesting, the company logo is displayed

![image](https://github.com/peviitor-ro/firme-peviitor/assets/122023703/e4cf36a1-c2af-4d5f-9410-655240f95b44)
