### ISSUE TITLE
Thoughtworks - LOGO NOT FOUND

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/firme-peviitor#51]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for the company "Thoughtworks"
3. Check the logo

EXPECTED RESULTS:
The logo for the company "Thoughtworks" must be the same as the original logo

ACTUAL RESULTS:
The message "Logo not found" is displayed instead of the logo

![image](https://github.com/peviitor-ro/firme-peviitor/assets/122023703/d47df8dc-89cc-49d3-82ef-3cd1f8ae3084)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
After retesting, the company logo is displayed

![image](https://github.com/peviitor-ro/firme-peviitor/assets/122023703/b1f6ee66-86d2-45ba-b215-a8c14df5f99e)
