### ISSUE TITLE
Tremend - The company logo is displayed 2 times on firme.peviitor.ro 

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/firme-peviitor#52]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for the company "Tremend"
3. Check the logo

EXPECTED RESULTS:
The "Tremend" Company logo appears once

ACTUAL RESULTS:
The "Tremend" Company logo appears 2 times

![image](https://github.com/peviitor-ro/firme-peviitor/assets/122023703/cdea6b45-0791-4d63-ab4a-adc334ac0534)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
After retesting, the "Tremend" Company logo appears once

![image](https://github.com/peviitor-ro/firme-peviitor/assets/122023703/c4c474df-3511-4455-b004-99a7920a4300)
