### ISSUE TITLE
Tickbird - LOGO NOT FOUND

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/firme-peviitor#53]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for the company "Tickbird"
3. Check the logo

EXPECTED RESULTS:
The logo for the company "Tickbird" must be the same as the original logo

ACTUAL RESULTS:
The message "Logo not found" is displayed instead of the logo

![image](https://github.com/peviitor-ro/firme-peviitor/assets/122023703/0c2be37c-5dd5-4660-ae3c-51eb67526121)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
After retesting, the company logo is displayed
![image](https://github.com/peviitor-ro/firme-peviitor/assets/122023703/08c32f2b-9b01-49a3-9b20-b2939e196ff1)
