### ISSUE TITLE
Quantrabbit - LOGO NOT FOUND

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/firme-peviitor#54]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for the company "Quantrabbit"
3. Check the logo

EXPECTED RESULTS:
The logo for the company "Quantrabbit" must be the same as the original logo

ACTUAL RESULTS:
The message "Logo not found" is displayed instead of the logo

![image](https://github.com/peviitor-ro/firme-peviitor/assets/122023703/3f73dfed-a527-448d-b8e1-ec1e4ff71036)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
After retesting, the company logo is displayed
![image](https://github.com/peviitor-ro/firme-peviitor/assets/122023703/2baaf920-f070-4d79-b499-63b19fd2d2f2)
