### ISSUE TITLE
Fortech - NO LOGO FOUND; The company logo is displayed 2 times 

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/firme-peviitor#55]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for the company "Fortech"
4. Check the logo

EXPECTED RESULTS:
The logo for the company "Fortech" must be the same as the original logo
The "Fortech" Company logo appears once

ACTUAL RESULTS:
The message "Logo not found" is displayed instead of the logo
The "Fortech" Company logo appears 2 times

![image](https://github.com/peviitor-ro/firme-peviitor/assets/122023703/d837d3d6-447e-473b-95ab-323f74b71dd3)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
After retesting, the logo for the company "Fortech" is the same as the original logo
The "Fortech" Company logo appears once


![image](https://github.com/peviitor-ro/firme-peviitor/assets/122023703/ef3de2b6-8707-48e4-9dc8-217ed8d18bc1)
