### ISSUE TITLE
Fortech- The company logo is displayed 2 times on the https://firme.peviitor.ro

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/firme-peviitor#56]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Search the company "Fortech"
3.Check the logo of the company

EXPECTED RESULTS:
The "Fortech" company  must have one logo

ACTUAL RESULTS:
The "Fortech" company logo appears 2 times

![image](https://github.com/peviitor-ro/firme-peviitor/assets/127322865/bef5dc5c-b59b-4fc4-b6cf-00faa9b9d440)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdinaIT** [comment]
Retesting. Problem solved. Works.
