### ISSUE TITLE
Nokia - The company logo is displayed 2 times on firme.peviitor.ro

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/firme-peviitor#59]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for the company "Nokia"
3. Check the logo

EXPECTED RESULTS:
The "Nokia" Company logo appears once

ACTUAL RESULTS:
The "Nokia" Company logo appears 2 times

![image](https://github.com/peviitor-ro/firme-peviitor/assets/71781611/66ebe48e-8d72-42fe-8163-05415d334612)

**Comment by lalalaurentiu** [comment]
fixed

**Comment by Geo843** [comment]
Re-tested, The "Nokia" Company logo appears once.
