### ISSUE TITLE
Fga - The company logo is displayed 2 times on firme.peviitor.ro

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/firme-peviitor#60]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for the company "Fga"
3. Check the logo

EXPECTED RESULTS:
The "Fga" Company logo appears once

ACTUAL RESULTS:
The "Fga" Company logo appears 2 times
The first logo "FGA Romania" return the message "page not found"

![image](https://github.com/peviitor-ro/firme-peviitor/assets/122023703/4f62c16b-2217-47ef-93dd-395539318198)

![image](https://github.com/peviitor-ro/firme-peviitor/assets/122023703/23803330-45aa-4950-bbfb-9ad6b002d664)
![image](https://github.com/peviitor-ro/firme-peviitor/assets/122023703/98b80576-c66e-457d-906d-0bd55d0e7146)

**Comment by lalalaurentiu** [comment]
fixed

**Comment by AdrianaCionca** [comment]
After retesting, the "Fga" Company logo appears once

![Image](https://github.com/peviitor-ro/firme-peviitor/assets/122023703/059496b4-2f0f-481d-8298-0549e7c4146c)
