### ISSUE TITLE
Kellanova - Company's name is duplicated and can be found under the wrong logo

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/firme-peviitor#61]
ENVIROMENT: production
COMPANY: Kellanova
URL: [Kellanova peviitor.ro](https://scrapers.peviitor.ro/src/kellanova/index.html)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in browser.

Steps:

1. In the search bar write "Kellanova".
2. Examine the logos listed along with the corresponding company names beneath them, and click on each for verification.

Expected result:
Entering the company's name into the search bar should reveal the accurate logo and corresponding name.

Actual result:
The name of the company has been replicated and is incorrectly associated with the wrong logo.
*Additional info: All 4 buttons lead to Kellanona webpages.

<img width="1388" alt="Screenshot 2023-11-27 at 12 44 05" src="https://github.com/peviitor-ro/Scrapers-UI/assets/103507535/e281b687-7f56-47b2-b651-2a0ac1b7e3b5">

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by iBixee** [comment]
Thank you!
