### ISSUE TITLE
Gazduirejocuri - The company logo is displayed 2 times on firme.peviitor.ro   

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/firme-peviitor#65]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser.
2. Search for the company " Gazduirejocuri ".
3. Check the logo.

EXPECTED RESULTS:
The "Gazduirejocuri " Company logo appears once.

ACTUAL RESULTS:
The "Gazduirejocuri " Company logo appears 2 times.

![image](https://github.com/peviitor-ro/firme-peviitor/assets/71781611/c5894097-6dfa-463e-b110-d6de58de016a)

**Comment by lalalaurentiu** [comment]
don't put this bug on scrapers because scrapers.peviitor.ro has no duplicates, 
<img width="1440" alt="Screenshot 2023-12-06 at 15 25 53" src="https://github.com/peviitor-ro/firme-peviitor/assets/67306273/cc07b2fb-55fd-47b6-9139-4088aad6b384">
put it in the firme-peviitor repository

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by Geo843** [comment]
Re-tested, The "Gazduirejocuri " Company logo appears once.
