### ISSUE TITLE
Segula- Different number of jobs on peviitor.ro then the number of jobs on https://jobs.smartrecruiters.com/?company=SegulaTechnologies&keyword=romania

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/firme-peviitor#69]
ENVIROMENT: production
URL: https://peviitor.ro/rezultate?q=Segula&country=Rom%C3%A2nia&page=1
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1) Open URL in browser
2) Check 'Locuri de munca' section

EXPECTED RESULTS:
 The number of jobs is the same on peviitor.ro as the numbers of jobs on https://jobs.smartrecruiters.com/?company=SegulaTechnologies&keyword=romania

ACTUAL RESULTS:
 The number of jobs is different on peviitor.ro ( 33 ) then the number of jobs on https://jobs.smartrecruiters.com/?company=SegulaTechnologies&keyword=romania ( 28 )

![cap033](https://github.com/peviitor-ro/firme-peviitor/assets/72222644/49858176-eae7-4401-88a5-3b090d0f94b9)

![cap034](https://github.com/peviitor-ro/firme-peviitor/assets/72222644/63686ffb-439f-433d-a835-103c4bf2179a)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
After retesting the number of jobs on peviito.ro is the same as the number of jobs on company website
