### ISSUE TITLE
Syncrosoft - The company logo is displayed 2 times on firme.peviitor.ro 

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/firme-peviitor#70]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for the company "Syncrosoft"
3. Check the logo

EXPECTED RESULTS:
The "Syncrosoft" Company logo appears once

ACTUAL RESULTS:
The "Syncrosoft" Company logo appears 2 times

![image](https://github.com/peviitor-ro/firme-peviitor/assets/122023703/f492f10a-a17d-435f-bea8-a4decf0ff442)

**Comment by lalalaurentiu** [comment]
fixed

**Comment by AdrianaCionca** [comment]
After retesting, the "Syncrosoft" Company logo appears once

![Image](https://github.com/peviitor-ro/firme-peviitor/assets/122023703/af07ac62-5d9f-4fe5-9413-38a5d40a540c)
