### ISSUE TITLE
pwc -The company name appears duplicated together with the logo

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/firme-peviitor#71]
ENVIROMENT: production
COMPANY: pwc
URL: [pwc peviitor.ro](https://firme.peviitor.ro/)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://firme.peviitor.ro/) must be open in browser.

Steps:
1. Click on Firme from footer.
2. Enter pwc in the search bar.

Expected result:
The company name appears along with the logo.

Actual result:
The company name appears duplicated together with the logo.

<img width="533" alt="Screenshot at Dec 07 13-15-45" src="https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/b1ffb009-c5f9-4d79-bf15-b2585563ec03">

**Comment by lalalaurentiu** [comment]
Fixed!
