### ISSUE TITLE
Bakertilly company is displayed twice on firme.peviitor.ro

### ISSUE THREAD

**Issue by RaresCode** [peviitor-ro/firme-peviitor#74]
**Environment**
 - Device: Desktop
 - OS: Windows 10
 - Browser Chrome
 - Version 120

**Steps to reproduce**
1. Go to "https://firme.peviitor.ro/"
2. Type "bakertilly" in the search field

**Expected Result**
 - The "bakertilly" company is displayed only once after typing "bakertilly" in the search field

**Actual Result**
 - The "bakertilly" company is displayed twice after typing "bakertilly" in the search field

**Screenshots**
![bug bakertilly](https://github.com/peviitor-ro/firme-peviitor/assets/91252395/694d4ecc-7529-4c98-a969-ae3900433239)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by RaresCode** [comment]
Fixed, closing this bug
