### ISSUE TITLE
Autonet - Company logo displayed 2 times

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/firme-peviitor#75]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for the company "Autonet"
3. Check the logo

EXPECTED RESULTS:
The "Autonet" Company logo appears once

ACTUAL RESULTS:
The "Autonet" Company logo appears 2 times

ATTACHMENTS:

![image](https://github.com/peviitor-ro/firme-peviitor/assets/71781611/4e0229e6-0569-49e4-87b0-4e61d6c5b52f)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by Geo843** [comment]
Re-tested,  The "Autonet" Company logo appears once.
