### ISSUE TITLE
Atp-group - Error Company Logo " Nu am gasit nimic pentru atp-group !"

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/firme-peviitor#76]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for the company "Atp-group"
3. Check the logo

EXPECTED RESULTS:
The "Atp-group" Company logo appears once 

ACTUAL RESULTS:
Error Company Logo " Nu am gasit nimic pentru atp-group !"

ATTACHMENTS:

![image](https://github.com/peviitor-ro/firme-peviitor/assets/71781611/ea43ee9b-4a21-4cc3-8ad1-f106bff7185b)

![image](https://github.com/peviitor-ro/firme-peviitor/assets/71781611/737007ad-4976-4cb9-9a55-b4bd227da2dd)

**Comment by lalalaurentiu** [comment]
atp-group changed in atpgroup

**Comment by Geo843** [comment]
Re-tested,  the "atpgroup" Company logo appears once
