### ISSUE TITLE
HCLTechnologies- Duplicate company

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/firme-peviitor#80]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for 'HCLTechnologies' Company
3. Check the result

EXPECTED RESULTS:
The company appears only once

ACTUAL RESULTS:
The company appears twice

![a46](https://github.com/peviitor-ro/firme-peviitor/assets/72222644/4ccdecdf-a4bf-473a-ae76-fc965101a6b2)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdiVanca** [comment]
After retesting, the company appears only once.
