### ISSUE TITLE
Borgwarner - The company logo is displayed 2 times on firme.peviitor.ro

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/firme-peviitor#82]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for the company "Borgwarner"
3. Check the logo

EXPECTED RESULTS:
The "Borgwarner" Company logo appears once

ACTUAL RESULTS:
The "Borgwarner" Company logo appears 2 times

![image](https://github.com/peviitor-ro/firme-peviitor/assets/122023703/17e64f57-d31b-4a82-9f12-3e05069e4171)

**Comment by lalalaurentiu** [comment]
Fixed
