### ISSUE TITLE
Allianz Tiriac- Duplicate company

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/firme-peviitor#83]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for 'HCLTechnologies' Company
3. Check the result

EXPECTED RESULTS:
The company appears only once

ACTUAL RESULTS:
The company appears twice: 1- 'AlliantTiriac' , 2- 'AllianzTiriac'

![a48](https://github.com/peviitor-ro/firme-peviitor/assets/72222644/0eb5708d-956b-4819-b59b-2937632db4b6)

**Comment by lalalaurentiu** [comment]
Fixed
