### ISSUE TITLE
Garmin - Duplicate company

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/firme-peviitor#88]
**Describe the bug**
Duplicate company

**To Reproduce**
1. Click on Firme from footer.
2. Enter Garmin in the search bar.

**Expected behavior**
The company name appears along with the logo.

**Screenshots**
<img width="420" alt="Screenshot at Jan 24 15-04-05" src="https://github.com/peviitor-ro/firme-peviitor/assets/137428958/a080ea23-b26b-4626-b3f5-84dc7f1100f7">

**Desktop**
 - OS: MacOS
 - Browser: Firefox

**Comment by lalalaurentiu** [comment]
Fixed
