### ISSUE TITLE
Smithfield - Logo not found

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/firme-peviitor#89]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for the company "Smithfield"
3. Check the logo

EXPECTED RESULTS:
The logo for the company "Smithfield" must be the same as the original logo

ACTUAL RESULTS:
The message "Logo not found" is displayed instead of the logo

![image](https://github.com/peviitor-ro/firme-peviitor/assets/122023703/a17cdc72-efb8-4b83-9c1d-ce45fc0ee27b)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdrianaCionca** [comment]
After retesting, the logo for the company "Smithfield" is the same as the original logo


![image](https://github.com/peviitor-ro/firme-peviitor/assets/122023703/a5e7b538-da76-43a2-91ad-894e5896c28a)
