### ISSUE TITLE
Fortech has 34 jobs on peviitor.ro and 46 on their website for Romania

### ISSUE THREAD

**Issue by CristianDoditoiu** [peviitor-ro/firme-peviitor#9]
**Steps to reproduce:**
Access peviitor.ro website
Click on "firme" button
Search for fortech in the search bar
Verify the number of jobs and click on some of the jobs listed in the list
Access https://www.fortech.ro/experienced-tech-professionals-jobs/

**Actual Results:**
Fortech has 34 jobs on peviitor.ro and 46 on their website for Romania. 

**Expected results:**
The number of jobs found on peviitor.ro should be the same as the one on https://www.fortech.ro/experienced-tech-professionals-jobs/

**Comment by CristianDoditoiu** [comment]
bug reopened

**Comment by sebiboga** [comment]
step 1) start the scraper from here: https://github.com/sebiboga/fortech/actions/workflows/jmeter.yml
step 2) check the number of jobs

if still reproducible... let me know

**Comment by CristianDoditoiu** [comment]
Verified. Status: Passed. It does not reproduce.
