### ISSUE TITLE
Vass - Duplicate company

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/firme-peviitor#90]
**Describe the bug**
Duplicate company

**To Reproduce**
1. Click on Firme from footer.
2. Enter Vass in the search bar.

**Expected behavior**
The company name appears along with the logo.

**Screenshots**
<img width="353" alt="Screenshot at Jan 25 15-23-07" src="https://github.com/peviitor-ro/firme-peviitor/assets/137428958/fb2fb5c5-eddd-4abe-afcd-bb122fe1ee8b">

**Desktop**
 - OS: MacOS
 - Browser: Safari

**Smartphone**
 - Device: MacBook Air
 - OS: MacOS
 - Browser Safari

**Comment by lalalaurentiu** [comment]
Fixed
