### ISSUE TITLE
BRD - Logo not found

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/firme-peviitor#93]
ENVIRONMENT: production
URL: https://firme.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for the company "BRD"
3. Check the logo

EXPECTED RESULTS:
The logo for the company 'BRD' must be the same as the original logo

ACTUAL RESULTS:
The message 'Logo not found' is displayed instead of the logo

![brd2](https://github.com/peviitor-ro/firme-peviitor/assets/72222644/27fac8b8-165f-4850-a887-0983c4ae76e2)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdiVanca** [comment]
After retesting, the company logo is displayed
