### ISSUE TITLE
P&G - Duplicate company

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/firme-peviitor#94]
**Describe the bug**
Duplicate company

**To Reproduce**
1. Click on Firme from footer.
2. Tape G in the search bar.

**Expected behavior**
The company name appears along with the logo.

**Screenshots**
<img width="777" alt="Screenshot at Feb 05 16-34-47" src="https://github.com/peviitor-ro/firme-peviitor/assets/137428958/8c13f416-fcff-4bd1-8f95-73a448f0ee49">

**Desktop**
 - OS: MacOS
 - Browser: Mozilla Firefox

**Smartphone**
 - Device: MacBook Air
 - OS: MacOS
 - Browser Mozilla Firefox

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdelinaGuliman** [comment]
I am reopening this issue because there are still duplicate companies
<img width="680" alt="Screenshot at Feb 16 15-22-01" src="https://github.com/peviitor-ro/firme-peviitor/assets/137428958/45ddb06e-be74-4094-ad44-5470be96de14">

**Comment by lalalaurentiu** [comment]
@andreireporter13 si @cristiol cine-l pastreaza si cine-l sterge?

**Comment by andreireporter13** [comment]
Îl cedez. Mai am până ajung la el.

**Comment by lalalaurentiu** [comment]
@andreireporter13 L-ai sters?

**Comment by andreireporter13** [comment]
E in buildul vechi. Deci nu rulează. Îl șterg diseară.
